/**
 * Bug reproduction test for GitHub workflow missing latest-*.yml files
 *
 * Bug: GitHub release workflow doesn't upload latest-mac.yml and latest-linux.yml files
 * Expected: Release workflow should upload all files needed by electron-updater including latest-*.yml
 * Actual: Workflow only uploads .dmg, .AppImage, and manifest.json but misses latest-*.yml files
 * Bug report: bug-reports/auto-update-404-error-report.md
 *
 * Root cause: .github/workflows/release.yml "files:" section missing latest-*.yml pattern
 * Impact: electron-updater's default GitHub provider can't find latest-mac.yml, causing 404 errors
 */

import { describe, it, expect } from '@jest/globals';
import { readFileSync } from 'fs';
import { join } from 'path';
import YAML from 'yaml';

describe('Bug: GitHub workflow missing latest-*.yml upload', () => {
  it('verifies release.yml includes latest-*.yml files in upload list', () => {
    // BUG FIX VERIFICATION:
    // The release workflow must upload latest-*.yml files generated by electron-builder
    // These files are required by electron-updater's default GitHub provider
    // Bug report: bug-reports/auto-update-404-error-report.md
    // Fixed: 2025-12-07

    const workflowPath = join(__dirname, '../../../.github/workflows/release.yml');
    const workflowContent = readFileSync(workflowPath, 'utf-8');
    const workflow = YAML.parse(workflowContent);

    // Navigate to the create-release job
    const createReleaseJob = workflow.jobs['create-release'];
    expect(createReleaseJob).toBeDefined();

    // Find the "Create GitHub Release" step
    const releaseStep = createReleaseJob.steps.find(
      (step: { name: string }) => step.name === 'Create GitHub Release'
    );
    expect(releaseStep).toBeDefined();

    // Get the files list
    const filesPattern = releaseStep.with.files;
    expect(filesPattern).toBeDefined();
    expect(typeof filesPattern).toBe('string');

    // REGRESSION TEST: Verify the fix is in place
    // The workflow MUST include a pattern that matches latest-*.yml files
    // This ensures electron-builder's generated latest-mac.yml and latest-linux.yml
    // are uploaded to GitHub releases for electron-updater to use
    expect(filesPattern).toContain('.yml');

    // Verify the pattern includes the correct path prefix
    expect(filesPattern).toContain('release-artifacts/**/*.yml');

    // Also verify other required files are still present (no regression)
    expect(filesPattern).toContain('.dmg');
    expect(filesPattern).toContain('.AppImage');
    expect(filesPattern).toContain('manifest.json');
  });

  it('documents the expected files in a GitHub release', () => {
    // This test documents what files SHOULD be in a GitHub release
    // after electron-builder packages the app

    // Expected files for version X.Y.Z:
    const expectedFiles = [
      // macOS artifacts
      'SlimChat-X.Y.Z.dmg',                    // macOS installer
      'SlimChat-X.Y.Z-mac.zip',                // macOS zip (alternate format)
      'latest-mac.yml',                        // electron-updater metadata for macOS

      // Linux artifacts
      'SlimChat-X.Y.Z-x86_64.AppImage',        // Linux AppImage
      'latest-linux.yml',                      // electron-updater metadata for Linux

      // Custom manifest (RSA-signed)
      'manifest.json',                         // Custom update manifest with signatures
    ];

    // The workflow's upload pattern should match ALL of these
    const patterns = [
      'release-artifacts/**/*.dmg',
      'release-artifacts/**/*.AppImage',
      'release-artifacts/**/*.yml',            // Matches latest-mac.yml and latest-linux.yml
      'release-artifacts/**/manifest.json',
    ];

    // Verify our expected files would be matched by the patterns
    expect(expectedFiles.length).toBeGreaterThan(0);
    expect(patterns.length).toBe(4);

    // This is a documentation test - it always passes
    expect(true).toBe(true);
  });
});
