/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is auto-generated by scripts/generate-migrations-map.ts
 * during the build process. It provides compile-time migration discovery
 * for ASAR archive compatibility.
 */

import * as migration0 from './migrations/20251210120000_create_app_state_table';
import * as migration1 from './migrations/20251212100000_create_nostling_tables';
import * as migration2 from './migrations/20251213000000_add_theme_to_identities';
import * as migration3 from './migrations/20251213120000_add_event_id_unique_constraint';
import * as migration4 from './migrations/20251213130000_add_contacts_unique_constraint';
import * as migration5 from './migrations/20251214100000_add_contact_deleted_at';
import * as migration6 from './migrations/20251214200000_add_message_is_read';
import * as migration7 from './migrations/20251215100000_add_private_profile_tables';
import * as migration8 from './migrations/20251218100000_add_p2p_connection_tables';
import * as migration9 from './migrations/20251219100000_add_p2p_replay_protection';
import * as migration10 from './migrations/20251219200000_add_message_kind';

export interface Migration {
  up: (knex: any) => Promise<void>;
  down?: (knex: any) => Promise<void>;
}

export const MIGRATIONS_MAP: Record<string, Migration> = {
  '20251210120000_create_app_state_table': migration0,
  '20251212100000_create_nostling_tables': migration1,
  '20251213000000_add_theme_to_identities': migration2,
  '20251213120000_add_event_id_unique_constraint': migration3,
  '20251213130000_add_contacts_unique_constraint': migration4,
  '20251214100000_add_contact_deleted_at': migration5,
  '20251214200000_add_message_is_read': migration6,
  '20251215100000_add_private_profile_tables': migration7,
  '20251218100000_add_p2p_connection_tables': migration8,
  '20251219100000_add_p2p_replay_protection': migration9,
  '20251219200000_add_message_kind': migration10,
};

export const MIGRATION_NAMES: string[] = [
  '20251210120000_create_app_state_table',
  '20251212100000_create_nostling_tables',
  '20251213000000_add_theme_to_identities',
  '20251213120000_add_event_id_unique_constraint',
  '20251213130000_add_contacts_unique_constraint',
  '20251214100000_add_contact_deleted_at',
  '20251214200000_add_message_is_read',
  '20251215100000_add_private_profile_tables',
  '20251218100000_add_p2p_connection_tables',
  '20251219100000_add_p2p_replay_protection',
  '20251219200000_add_message_kind',
];
