/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is auto-generated by scripts/generate-migrations-map.ts
 * during the build process. It provides compile-time migration discovery
 * for ASAR archive compatibility.
 */

import * as migration0 from './migrations/20251210120000_create_app_state_table';
import * as migration1 from './migrations/20251212100000_create_nostling_tables';

export interface Migration {
  up: (knex: any) => Promise<void>;
  down?: (knex: any) => Promise<void>;
}

export const MIGRATIONS_MAP: Record<string, Migration> = {
  '20251210120000_create_app_state_table': migration0,
  '20251212100000_create_nostling_tables': migration1,
};

export const MIGRATION_NAMES: string[] = [
  '20251210120000_create_app_state_table',
  '20251212100000_create_nostling_tables',
];
